# Flutter official lint rules
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # ⚠️ এই rule পুরোনো Flutter SDK গুলোতে নেই, তাই comment করে রাখা হলো
    # type_literal_in_constant_pattern: false
