name: mk_share
description: A cyberpunk-themed local file sharing app.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # For file picker (selecting files)
  file_picker: ^5.5.0

  # For getting download folder
  path_provider: ^2.0.15

  # For sending HTTP request
  http: ^0.13.5

  # For generating QR code
  qr_flutter: ^4.1.0

  # For scanning QR code (modification of qr_code_scanner)
  mobile_scanner: ^3.5.6

  # For managing permissions
  permission_handler: ^10.2.0

  # For splash screen animation
  lottie: ^2.3.2

  # For staggered animation
  flutter_staggered_animations: ^1.1.1

  # For animated text
  animated_text_kit: ^4.2.2

  # For opening links on websites
  url_launcher: ^6.1.10

  # For saving settings
  shared_preferences: ^2.1.1

  # For checking network status
  connectivity_plus: ^5.0.1

  # For getting device information
  device_info_plus: ^11.3.0 # <--- This version has been updated to avoid conflicts.

  # For using SVG images
  flutter_svg: ^2.0.5

  # For shimmer effects
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add asset files here
  assets:
    - assets/animations/