name: mk_share
description: A local file sharing app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: ^6.2.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  http: ^1.1.0
  network_info_plus: ^4.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  simple_animations: ^5.0.0
  flutter_neumorphic: ^3.2.0
  lottie: ^3.1.2
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
